# Generated by Django 4.0 on 2023-04-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangalorejobs',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='chennaijobs',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='hydjobs',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='punejobs',
            old_name='tittle',
            new_name='title',
        ),
    ]
